import botGastosImg from "../assets/bot-gastos.png";
import DashboardVentasImg from "../assets/DashboardVentas.png";
import PortfolioImg from "../assets/Portfolio.png";

export const PROJECT_DETAILS = {
  "Dashboard Analytics": [
    {
      title: "Dashboard de Ventas CloudCoders",
      detail: "Panel completo de ventas con más de 30 métricas, filtros dinámicos por región, producto y período. Incluye análisis predictivo con IA para proyecciones mensuales.",
      tech: ["Power BI", "DAX", "Claude AI", "REST API"],
      accent: "#8F00FF",
      link: "#",
      status: "dev",
      year: "2026",
      image: DashboardVentasImg,
    },
    {
      title: "Dashboard Financiero CAJA",
      detail: "Sistema de control financiero con 40+ medidas DAX, tema oscuro personalizado y análisis de variaciones YoY. Integración directa con bases de datos SQL.",
      tech: ["Power BI", "DAX", "SQL", "JSON Theme"],
      accent: "#F2C811",
      link: null,
      status: "private",
      year: "2024",
      image: null,
    },
    {
      title: "Reporte de Marketing Digital",
      detail: "Dashboard de marketing con seguimiento de campañas en múltiples canales, análisis de ROI y segmentación de audiencia por comportamiento.",
      tech: ["Power BI", "Google Analytics", "DAX"],
      accent: "#4ffbdf",
      link: null,
      status: "dev",
      year: "2025",
      image: null,
    },
  ],
  "Automatización CRM": [
    {
      title: "Bot de Gastos Personales",
      detail: "Workflow automatizado que recibe gastos por texto, voz, imagen o PDF desde Telegram. Un agente IA extrae los datos y los guarda simultáneamente en Google Sheets y Supabase.",
      tech: ["n8n", "Telegram", "Claude AI", "Supabase", "Google Sheets"],
      accent: "#EA4B71",
      link: "#",
      status: "live",
      year: "2024",
      image: botGastosImg,
    },
    {
      title: "Pipeline de Captación CRM",
      detail: "Sistema completo de captación y nutrición de leads con scoring automático, notificaciones por WhatsApp y sincronización con CRM. Reduce 20h de trabajo manual semanales.",
      tech: ["n8n", "Webhooks", "API", "WhatsApp"],
      accent: "#ffc75f",
      link: null,
      status: "private",
      year: "2025",
      image: null,
    },
    {
      title: "Soporte AI Automatizado",
      detail: "Agente de soporte inteligente integrado en web y WhatsApp. Responde consultas frecuentes, escala tickets complejos y genera reportes de satisfacción automáticamente.",
      tech: ["n8n", "Claude AI", "WhatsApp API", "Webhook"],
      accent: "#C46CFF",
      link: null,
      status: "live",
      year: "2025",
      image: null,
    },
  ],
  "App Web Reactiva": [
    {
      title: "Portfolio CloudCoders",
      detail: "Portfolio personal con modo oscuro/claro, animaciones de scroll, orbe 3D interactivo con logos orbitando, sección de precios dinámica y formulario de contacto.",
      tech: ["React JS", "Vite", "CSS Modules", "Context API"],
      accent: "#A8EB12",
      link: "#",
      status: "live",
      year: "2026",
      image: PortfolioImg,
    },
    {
      title: "Dashboard Admin SaaS",
      detail: "Aplicación SPA con autenticación, gestión de usuarios, roles y permisos. Arquitectura modular con hooks personalizados, lazy loading y optimización de rendimiento.",
      tech: ["React JS", "Tailwind CSS", "REST API", "JWT"],
      accent: "#38BDF8",
      link: null,
      status: "dev",
      year: "2025",
      image: null,
    },
    {
      title: "Landing Page con IA",
      detail: "Landing de alta conversión con chatbot de Claude AI integrado, animaciones con Framer Motion, formulario inteligente y analítica de comportamiento en tiempo real.",
      tech: ["React JS", "Claude AI", "Framer Motion", "Vite"],
      accent: "#FF9A00",
      link: null,
      status: "dev",
      year: "2025",
      image: null,
    },
  ],
};
